- name: Kill Fleet Watchdog
  description: Monitors robot status and /kill_fleet topic and kills fleet.
  restart_timeout: -1
  monitors:
    - monitor_type: TopicPublishedAnyType
      topic: /kill_fleet
  actions:
    - action_type: KillFleet