- name: Kill Fleet Watchdog
  description: Monitors robot status and /kill_fleet topic and kills fleet.
  restart_timeout: -1
  monitors:
    - monitor_type: TopicPublishedAnyType
      topic: /kill_fleet
    - monitor_type: RobotDown
      topic: /front/scan
      max_duration: 10
      num_robots: 5
    - monitor_type: RobotDown
      topic: /odometry/filtered
      max_duration: 10
      num_robots: 5
  actions:
    - action_type: KillFleet